-- Migration: Add 70 more AI job opportunities
-- Date: 2025-10-16
-- Total jobs after this migration: 108 (38 existing + 70 new)

-- FINANCE (10 jobs)
INSERT INTO workers (id, name, title, tagline, description, skills, rate_monthly, category, availability, setup_time) VALUES
('ai-bookkeeper', 'AI Bookkeeper Assistant', 'Small Business Accounting', 'Categorize transactions and reconcile accounts', 'Use AI to categorize expenses, match transactions, flag anomalies, and prepare financial summaries for small businesses. Handle receipt processing, expense categorization, and monthly reconciliations with Claude and accounting software integration.', '["Claude", "QuickBooks", "Excel"]', 1500, 'finance', 'Business hours', '1 week'),
('ai-tax-preparer', 'AI Tax Preparation Specialist', 'Tax Season Support', 'Prepare tax returns and find deductions', 'Assist with tax preparation by analyzing financial records, identifying deductions, organizing documentation, and preparing draft returns. Use AI to stay current with tax law changes and optimize deductions for clients.', '["ChatGPT", "TurboTax", "Excel"]', 2200, 'finance', 'Flexible', '2 weeks'),
('ai-financial-analyst', 'AI Financial Analyst', 'Investment Research', 'Analyze markets and create investment reports', 'Research stocks, bonds, and market trends using AI-powered analysis. Create detailed investment reports, track portfolio performance, and identify opportunities. Synthesize data from multiple sources into actionable insights.', '["Claude", "Bloomberg Terminal", "Python"]', 2800, 'finance', 'Business hours', '2 weeks'),
('ai-invoice-manager', 'AI Invoice Manager', 'Billing Automation', 'Create, send, and track invoices automatically', 'Automate invoice creation, sending, and payment tracking. Use AI to follow up on overdue payments, reconcile received payments, and generate payment reports. Integrate with accounting systems for seamless workflow.', '["ChatGPT", "QuickBooks", "Stripe"]', 1200, 'finance', '24/7', '3 days'),
('ai-budget-planner', 'AI Budget Planning Assistant', 'Personal & Business Budgets', 'Create and monitor budgets with AI insights', 'Help individuals and businesses create realistic budgets using AI analysis of spending patterns. Monitor budget adherence, flag overspending, suggest optimizations, and generate monthly budget reports with actionable recommendations.', '["Claude", "Excel", "Mint"]', 1400, 'finance', 'Flexible', '1 week'),
('ai-expense-auditor', 'AI Expense Auditor', 'Fraud Detection', 'Audit expenses and flag suspicious patterns', 'Review expense reports for policy violations, duplicate claims, and fraud indicators. Use AI to detect unusual patterns, verify receipts, and ensure compliance with company policies. Generate detailed audit reports.', '["ChatGPT", "Expensify", "Excel"]', 1800, 'finance', 'Business hours', '1 week'),
('ai-payroll-assistant', 'AI Payroll Assistant', 'Payroll Processing', 'Calculate pay, deductions, and tax withholdings', 'Assist with payroll processing by calculating hours, overtime, deductions, and tax withholdings. Generate pay stubs, track PTO, and ensure compliance with labor laws. Use AI to catch errors before processing.', '["Claude", "Gusto", "Excel"]', 1600, 'finance', 'Business hours', '1 week'),
('ai-credit-analyst', 'AI Credit Risk Analyst', 'Loan Assessment', 'Evaluate creditworthiness and loan applications', 'Analyze credit applications using AI-powered risk assessment. Review credit reports, income documentation, and payment history to make lending recommendations. Generate detailed credit analysis reports with risk scores.', '["ChatGPT", "Excel", "Python"]', 2400, 'finance', 'Business hours', '2 weeks'),
('ai-collections-specialist', 'AI Collections Specialist', 'Accounts Receivable', 'Recover overdue payments professionally', 'Use AI to craft professional collection messages, schedule follow-ups, negotiate payment plans, and track collection success rates. Maintain positive customer relationships while recovering outstanding balances.', '["Claude", "Salesforce", "Email"]', 1700, 'finance', 'Business hours', '1 week'),
('ai-financial-reporter', 'AI Financial Reporter', 'Financial Reporting', 'Generate monthly financial statements', 'Create comprehensive financial reports including P&L statements, balance sheets, and cash flow reports. Use AI to analyze trends, highlight key metrics, and provide executive summaries with actionable insights.', '["ChatGPT", "QuickBooks", "Excel"]', 2000, 'finance', 'Business hours', '1 week'),

-- CUSTOMER SERVICE (10 jobs)
('ai-chat-support', 'AI Chat Support Agent', '24/7 Customer Chat', 'Handle customer inquiries via live chat', 'Provide instant customer support through chat using AI to understand questions, search knowledge bases, and deliver accurate answers. Escalate complex issues to humans while handling routine inquiries autonomously with high customer satisfaction.', '["Claude", "Zendesk", "Intercom"]', 1300, 'customer-service', '24/7', '3 days'),
('ai-ticket-router', 'AI Ticket Router', 'Smart Ticket Management', 'Categorize and route support tickets intelligently', 'Analyze incoming support tickets using AI to categorize by urgency, department, and issue type. Route to appropriate specialists, suggest relevant knowledge base articles, and prioritize based on SLA requirements.', '["ChatGPT", "Jira", "Zendesk"]', 1100, 'customer-service', '24/7', '3 days'),
('ai-help-center-creator', 'AI Help Center Content Writer', 'Knowledge Base Building', 'Write and maintain help documentation', 'Create comprehensive help articles, FAQs, and tutorials using AI. Analyze common support questions to identify documentation gaps, update existing articles, and ensure content is clear, accurate, and SEO-optimized.', '["Claude", "Notion", "WordPress"]', 1600, 'customer-service', 'Flexible', '1 week'),
('ai-customer-feedback-analyst', 'AI Feedback Analyst', 'Survey & Review Analysis', 'Analyze customer feedback and sentiment', 'Use AI to analyze customer surveys, reviews, and feedback across all channels. Identify trends, sentiment patterns, and actionable insights. Generate monthly reports with recommendations for improvement.', '["ChatGPT", "SurveyMonkey", "Excel"]', 1500, 'customer-service', 'Flexible', '1 week'),
('ai-email-support', 'AI Email Support Specialist', 'Email Customer Service', 'Respond to customer emails professionally', 'Handle customer email inquiries using AI to draft professional, empathetic responses. Check order status, process returns, answer product questions, and resolve issues while maintaining brand voice and high satisfaction scores.', '["Claude", "Gmail", "Zendesk"]', 1200, 'customer-service', '24/7', '3 days'),
('ai-onboarding-specialist', 'AI Customer Onboarding Guide', 'New Customer Setup', 'Guide new customers through product setup', 'Create personalized onboarding experiences using AI. Send welcome sequences, provide setup tutorials, answer initial questions, and ensure customers achieve their first success quickly. Track onboarding completion rates.', '["ChatGPT", "Intercom", "Mailchimp"]', 1400, 'customer-service', 'Business hours', '1 week'),
('ai-refund-processor', 'AI Refund & Returns Manager', 'Returns Processing', 'Handle refunds and returns efficiently', 'Process refund and return requests using AI to verify eligibility, generate return labels, process refunds, and update inventory. Handle edge cases and maintain positive customer relationships during the returns process.', '["Claude", "Shopify", "Zendesk"]', 1300, 'customer-service', 'Business hours', '3 days'),
('ai-social-media-responder', 'AI Social Media Support', 'Social Customer Care', 'Respond to customer questions on social media', 'Monitor social media channels for customer questions and concerns. Use AI to craft on-brand responses, resolve issues publicly, and escalate sensitive matters. Track response times and customer sentiment.', '["ChatGPT", "Hootsuite", "Twitter"]', 1500, 'customer-service', '24/7', '1 week'),
('ai-complaint-resolver', 'AI Complaint Resolution Specialist', 'Difficult Customer Situations', 'De-escalate and resolve customer complaints', 'Handle escalated customer complaints using AI to analyze the situation, review history, and craft empathetic resolution proposals. Turn unhappy customers into advocates through thoughtful problem-solving and compensation when appropriate.', '["Claude", "Zendesk", "Salesforce"]', 1800, 'customer-service', 'Business hours', '1 week'),
('ai-live-chat-trainer', 'AI Chat Training Specialist', 'Chatbot Improvement', 'Train and optimize AI chatbots', 'Analyze chatbot conversations to identify improvement opportunities. Update training data, refine responses, add new intents, and optimize conversation flows. Monitor chatbot performance metrics and customer satisfaction scores.', '["ChatGPT", "Dialogflow", "Python"]', 2000, 'customer-service', 'Flexible', '2 weeks'),

-- CONTENT CREATION (10 jobs)
('ai-video-scripter', 'AI Video Script Writer', 'YouTube & TikTok Scripts', 'Write engaging video scripts for creators', 'Create compelling video scripts for YouTube, TikTok, and Instagram using AI. Research trending topics, write hooks, structure content for engagement, and optimize scripts for platform algorithms. Include calls-to-action and SEO keywords.', '["Claude", "YouTube", "TikTok"]', 1600, 'content-creation', 'Flexible', '1 week'),
('ai-podcast-producer', 'AI Podcast Producer', 'Podcast Production', 'Produce podcast episodes from research to show notes', 'Research topics, create episode outlines, write show notes, generate timestamps, and create promotional content for podcast episodes. Use AI to suggest guests, create interview questions, and optimize episode descriptions for discovery.', '["ChatGPT", "Descript", "Notion"]', 1800, 'content-creation', 'Flexible', '1 week'),
('ai-newsletter-writer', 'AI Newsletter Writer', 'Email Newsletter Creation', 'Write and send engaging email newsletters', 'Create weekly or monthly newsletters using AI to curate content, write compelling copy, create subject lines, and optimize for open rates. Analyze performance metrics and continuously improve engagement.', '["Claude", "Mailchimp", "Substack"]', 1400, 'content-creation', 'Flexible', '1 week'),
('ai-blog-writer', 'AI Blog Content Writer', 'SEO Blog Posts', 'Write SEO-optimized blog posts at scale', 'Research keywords, write comprehensive blog posts, optimize for SEO, and create content calendars. Use AI to ensure content is original, well-structured, and valuable to readers while ranking well in search engines.', '["ChatGPT", "WordPress", "Surfer SEO"]', 1500, 'content-creation', 'Flexible', '1 week'),
('ai-social-media-manager', 'AI Social Media Content Manager', 'Social Content Calendar', 'Create and schedule social media content', 'Plan content calendars, create posts for multiple platforms, write captions, suggest hashtags, and schedule posts. Use AI to analyze engagement patterns and optimize posting times and content types for each platform.', '["Claude", "Buffer", "Canva"]', 1700, 'content-creation', 'Flexible', '1 week'),
('ai-copywriter', 'AI Marketing Copywriter', 'Ad Copy & Landing Pages', 'Write persuasive marketing copy that converts', 'Create compelling ad copy, landing pages, product descriptions, and marketing emails. Use AI to test different angles, write multiple variations, and optimize copy based on conversion data and customer psychology.', '["ChatGPT", "Google Ads", "Unbounce"]', 2000, 'content-creation', 'Flexible', '1 week'),
('ai-technical-writer', 'AI Technical Documentation Writer', 'Software Documentation', 'Write clear technical documentation', 'Create user guides, API documentation, tutorials, and technical specifications. Use AI to explain complex concepts clearly, maintain consistency, and keep documentation up-to-date with product changes.', '["Claude", "GitBook", "Markdown"]', 2200, 'content-creation', 'Business hours', '2 weeks'),
('ai-product-description-writer', 'AI Product Description Specialist', 'E-commerce Copy', 'Write compelling product descriptions', 'Create persuasive product descriptions for e-commerce sites using AI. Highlight benefits, include SEO keywords, maintain brand voice, and optimize for conversions. Scale to hundreds of products efficiently.', '["ChatGPT", "Shopify", "Amazon"]', 1300, 'content-creation', 'Flexible', '3 days'),
('ai-press-release-writer', 'AI Press Release Writer', 'PR & Media Relations', 'Write newsworthy press releases', 'Draft professional press releases for company announcements, product launches, and newsworthy events. Use AI to follow AP style, craft compelling headlines, and distribute to media outlets for maximum coverage.', '["Claude", "PR Newswire", "Google Docs"]', 1900, 'content-creation', 'Business hours', '1 week'),
('ai-content-repurposer', 'AI Content Repurposing Specialist', 'Multi-Platform Content', 'Transform content across different formats', 'Use AI to repurpose content across platforms: turn blog posts into social threads, podcasts into articles, videos into blog posts. Maximize content ROI by adapting for each platform''s unique format and audience.', '["ChatGPT", "Descript", "Canva"]', 1600, 'content-creation', 'Flexible', '1 week'),

-- SOFTWARE DEVELOPMENT (10 jobs)
('ai-code-documenter', 'AI Code Documentation Specialist', 'Developer Documentation', 'Document codebases and create developer guides', 'Use AI to analyze code and generate comprehensive documentation including function descriptions, API references, code examples, and architecture diagrams. Keep documentation in sync with code changes.', '["Claude", "GitHub", "JSDoc"]', 2000, 'software-development', 'Flexible', '1 week'),
('ai-bug-finder', 'AI Bug Detection Specialist', 'Code Quality Assurance', 'Find bugs and security vulnerabilities in code', 'Analyze code using AI to identify potential bugs, security vulnerabilities, code smells, and performance issues. Generate detailed reports with severity ratings and suggested fixes before code reaches production.', '["ChatGPT", "GitHub", "SonarQube"]', 2400, 'software-development', 'Flexible', '2 weeks'),
('ai-test-writer', 'AI Test Automation Writer', 'Automated Testing', 'Write unit tests and integration tests', 'Create comprehensive test suites using AI to ensure code coverage. Write unit tests, integration tests, and end-to-end tests. Maintain tests as code evolves and identify gaps in test coverage.', '["Claude", "Jest", "Cypress"]', 2200, 'software-development', 'Flexible', '2 weeks'),
('ai-code-reviewer', 'AI Code Review Assistant', 'Pull Request Reviews', 'Review code and provide constructive feedback', 'Review pull requests using AI to check for best practices, potential bugs, performance issues, and code style. Provide constructive feedback, suggest improvements, and ensure code quality standards are met.', '["ChatGPT", "GitHub", "GitLab"]', 2300, 'software-development', 'Flexible', '1 week'),
('ai-api-developer', 'AI API Integration Specialist', 'API Development', 'Build and integrate REST APIs', 'Design and implement REST APIs using AI assistance. Create endpoints, handle authentication, write API documentation, and integrate with third-party services. Test thoroughly and ensure proper error handling.', '["Claude", "Postman", "Node.js"]', 2600, 'software-development', 'Business hours', '2 weeks'),
('ai-database-optimizer', 'AI Database Optimization Specialist', 'Database Performance', 'Optimize database queries and schema', 'Analyze database performance using AI to identify slow queries, suggest indexes, optimize schema design, and improve query efficiency. Monitor database health and prevent performance degradation.', '["ChatGPT", "PostgreSQL", "SQL"]', 2500, 'software-development', 'Flexible', '2 weeks'),
('ai-code-refactorer', 'AI Code Refactoring Specialist', 'Code Improvement', 'Refactor legacy code for better maintainability', 'Use AI to identify refactoring opportunities in legacy codebases. Improve code structure, reduce complexity, eliminate duplication, and modernize outdated patterns while maintaining functionality.', '["Claude", "GitHub", "VS Code"]', 2400, 'software-development', 'Flexible', '2 weeks'),
('ai-devops-automator', 'AI DevOps Automation Engineer', 'CI/CD Pipelines', 'Automate deployment and infrastructure tasks', 'Create and maintain CI/CD pipelines using AI assistance. Automate testing, deployment, and infrastructure provisioning. Write infrastructure as code and implement monitoring and alerting.', '["ChatGPT", "GitHub Actions", "Docker"]', 2800, 'software-development', 'Flexible', '2 weeks'),
('ai-mobile-app-tester', 'AI Mobile App Testing Specialist', 'Mobile QA', 'Test mobile apps across devices and platforms', 'Use AI to create test plans, execute tests across devices, identify UI/UX issues, and ensure app quality. Test on iOS and Android, report bugs with detailed reproduction steps, and verify fixes.', '["Claude", "TestFlight", "Android Studio"]', 2100, 'software-development', 'Flexible', '1 week'),
('ai-tech-debt-manager', 'AI Technical Debt Analyst', 'Code Health Management', 'Identify and prioritize technical debt', 'Use AI to analyze codebases for technical debt including outdated dependencies, deprecated patterns, and maintainability issues. Create prioritized backlogs, estimate effort, and track debt reduction progress.', '["ChatGPT", "SonarQube", "GitHub"]', 2300, 'software-development', 'Flexible', '2 weeks'),

-- OPERATIONS (10 jobs)
('ai-project-manager', 'AI Project Manager Assistant', 'Project Coordination', 'Manage projects and keep teams on track', 'Use AI to create project plans, track milestones, send status updates, identify blockers, and keep stakeholders informed. Automate routine project management tasks while ensuring nothing falls through the cracks.', '["Claude", "Asana", "Slack"]', 2000, 'operations', 'Business hours', '1 week'),
('ai-meeting-coordinator', 'AI Meeting Coordinator', 'Calendar & Scheduling', 'Schedule meetings and manage calendars', 'Coordinate meetings across time zones using AI to find optimal times, send invites, prepare agendas, take notes, and distribute action items. Follow up on pending tasks and reschedule when conflicts arise.', '["ChatGPT", "Google Calendar", "Calendly"]', 1200, 'operations', 'Business hours', '3 days'),
('ai-data-entry-specialist', 'AI Data Entry Specialist', 'Data Processing', 'Enter and clean data accurately at scale', 'Process large volumes of data using AI assistance. Clean data, remove duplicates, standardize formats, validate entries, and import into databases or spreadsheets. Ensure accuracy while working at high speed.', '["Claude", "Excel", "Google Sheets"]', 900, 'operations', 'Flexible', '3 days'),
('ai-process-documenter', 'AI Process Documentation Specialist', 'SOP Creation', 'Document business processes and create SOPs', 'Create standard operating procedures using AI by observing workflows, interviewing team members, and documenting step-by-step processes. Maintain documentation as processes evolve and ensure clarity for new team members.', '["ChatGPT", "Notion", "Loom"]', 1500, 'operations', 'Flexible', '1 week'),
('ai-inventory-manager', 'AI Inventory Management Assistant', 'Stock Level Optimization', 'Track inventory and optimize stock levels', 'Monitor inventory levels using AI to predict demand, trigger reorders, prevent stockouts, and minimize excess inventory. Generate inventory reports and identify slow-moving items for clearance.', '["Claude", "Shopify", "Excel"]', 1400, 'operations', 'Business hours', '1 week'),
('ai-vendor-coordinator', 'AI Vendor Management Coordinator', 'Supplier Relations', 'Manage vendor relationships and procurement', 'Coordinate with vendors using AI to track orders, negotiate terms, process invoices, and maintain vendor databases. Monitor vendor performance, handle issues, and ensure timely delivery of goods and services.', '["ChatGPT", "Excel", "Email"]', 1600, 'operations', 'Business hours', '1 week'),
('ai-hr-recruiter', 'AI Recruiting Assistant', 'Talent Acquisition', 'Screen resumes and schedule interviews', 'Use AI to screen resumes, identify qualified candidates, send initial outreach, schedule interviews, and maintain candidate databases. Draft job descriptions and track applicants through the hiring funnel.', '["Claude", "LinkedIn", "Greenhouse"]', 1800, 'operations', 'Business hours', '1 week'),
('ai-travel-coordinator', 'AI Travel & Expense Coordinator', 'Business Travel', 'Book travel and manage expense reports', 'Coordinate business travel using AI to find optimal flights, hotels, and rental cars. Create detailed itineraries, track expenses, submit expense reports, and ensure policy compliance while optimizing costs.', '["ChatGPT", "Expedia", "Concur"]', 1300, 'operations', 'Business hours', '3 days'),
('ai-compliance-tracker', 'AI Compliance & License Tracker', 'Regulatory Compliance', 'Track licenses, permits, and compliance deadlines', 'Monitor compliance requirements using AI to track license renewals, permit expirations, and regulatory deadlines. Send renewal reminders, maintain compliance documentation, and ensure nothing expires or lapses.', '["Claude", "Excel", "Notion"]', 1700, 'operations', 'Business hours', '1 week'),
('ai-workflow-optimizer', 'AI Workflow Optimization Specialist', 'Process Improvement', 'Analyze and optimize business workflows', 'Use AI to analyze existing workflows, identify bottlenecks, suggest automation opportunities, and implement improvements. Measure efficiency gains and continuously optimize processes for speed and cost reduction.', '["ChatGPT", "Zapier", "Notion"]', 2100, 'operations', 'Flexible', '2 weeks'),

-- SALES (10 jobs)
('ai-cold-emailer', 'AI Cold Email Specialist', 'Outbound Sales Outreach', 'Write and send personalized cold emails at scale', 'Use AI to research prospects, write personalized cold emails, create follow-up sequences, and track responses. A/B test subject lines and copy to optimize open rates and book meetings with qualified prospects.', '["Claude", "Lemlist", "LinkedIn"]', 1800, 'sales', 'Business hours', '1 week'),
('ai-proposal-writer', 'AI Proposal & Quote Writer', 'Sales Proposals', 'Create winning proposals and quotes', 'Generate customized sales proposals using AI to understand client needs, highlight relevant experience, create pricing tables, and craft compelling executive summaries. Maintain proposal templates and track win rates.', '["ChatGPT", "PandaDoc", "Google Docs"]', 1900, 'sales', 'Business hours', '1 week'),
('ai-crm-manager', 'AI CRM Data Manager', 'Customer Database', 'Maintain and enrich CRM data', 'Keep CRM data clean and up-to-date using AI to enrich contacts, remove duplicates, update company information, and log interactions. Create custom reports, segment audiences, and ensure data quality.', '["Claude", "Salesforce", "HubSpot"]', 1500, 'sales', 'Flexible', '1 week'),
('ai-lead-qualifier', 'AI Lead Qualification Specialist', 'Inbound Lead Scoring', 'Score and qualify inbound leads', 'Use AI to analyze inbound leads, score based on fit and intent, enrich with company data, and route to appropriate sales reps. Track lead sources and conversion rates to optimize marketing spend.', '["ChatGPT", "HubSpot", "LinkedIn"]', 1600, 'sales', 'Business hours', '1 week'),
('ai-sales-researcher', 'AI Sales Research Specialist', 'Prospect Intelligence', 'Research prospects and companies for sales teams', 'Conduct deep research on target accounts using AI to gather company news, identify decision makers, understand pain points, and create sales intelligence briefs. Enable sales teams to approach prospects with valuable insights.', '["Claude", "LinkedIn", "Crunchbase"]', 1700, 'sales', 'Business hours', '1 week'),
('ai-objection-handler', 'AI Objection Handling Coach', 'Sales Enablement', 'Create responses to common sales objections', 'Use AI to analyze sales calls, identify common objections, and create effective responses. Build objection handling guides, train sales teams, and continuously refine responses based on what works.', '["ChatGPT", "Gong", "Google Docs"]', 1800, 'sales', 'Flexible', '1 week'),
('ai-contract-reviewer', 'AI Contract Review Specialist', 'Legal Document Review', 'Review sales contracts and identify risks', 'Analyze sales contracts using AI to identify unfavorable terms, flag legal risks, ensure compliance with company policies, and suggest modifications. Expedite contract review while protecting company interests.', '["Claude", "DocuSign", "Google Docs"]', 2200, 'sales', 'Business hours', '2 weeks'),
('ai-sales-forecaster', 'AI Sales Forecasting Analyst', 'Revenue Prediction', 'Forecast sales and predict pipeline conversion', 'Use AI to analyze sales pipeline, predict close rates, forecast revenue, and identify at-risk deals. Generate weekly forecasts, track accuracy, and provide insights to help sales leaders make data-driven decisions.', '["ChatGPT", "Salesforce", "Excel"]', 2000, 'sales', 'Business hours', '2 weeks'),
('ai-referral-coordinator', 'AI Referral Program Manager', 'Customer Referrals', 'Manage and grow customer referral programs', 'Automate referral programs using AI to invite customers to refer, track referrals, calculate commissions, and send rewards. Create referral campaigns and optimize program performance for maximum growth.', '["Claude", "ReferralCandy", "Mailchimp"]', 1400, 'sales', 'Flexible', '1 week'),
('ai-competitor-analyst', 'AI Competitive Intelligence Analyst', 'Market Research', 'Monitor competitors and market trends', 'Track competitor activities using AI to monitor pricing changes, new features, marketing campaigns, and customer reviews. Create competitive battle cards and market intelligence reports for sales teams.', '["ChatGPT", "SEMrush", "Google Alerts"]', 1900, 'sales', 'Flexible', '1 week'),

-- DESIGN (10 jobs)
('ai-logo-designer', 'AI Logo Design Assistant', 'Brand Identity', 'Create logo concepts and brand marks', 'Use AI tools to generate logo concepts, create variations, and refine designs based on client feedback. Provide multiple options in different styles, deliver final files in all required formats, and ensure brand consistency.', '["Midjourney", "Figma", "Adobe Illustrator"]', 1600, 'design', 'Flexible', '1 week'),
('ai-ui-designer', 'AI UI/UX Design Assistant', 'Interface Design', 'Design user interfaces and experiences', 'Create wireframes, mockups, and prototypes using AI assistance. Design intuitive user interfaces, conduct usability research, and iterate based on user feedback. Ensure accessibility and responsive design across devices.', '["Claude", "Figma", "Adobe XD"]', 2200, 'design', 'Flexible', '2 weeks'),
('ai-graphic-designer', 'AI Graphic Design Specialist', 'Marketing Graphics', 'Create graphics for social media and marketing', 'Design eye-catching graphics for social media, ads, presentations, and marketing materials. Use AI to generate concepts, maintain brand guidelines, and create templates for recurring design needs at scale.', '["Midjourney", "Canva", "Photoshop"]', 1500, 'design', 'Flexible', '1 week'),
('ai-presentation-designer', 'AI Presentation Designer', 'Pitch Decks & Slides', 'Design compelling presentation slides', 'Transform content into visually stunning presentations using AI. Create pitch decks, sales presentations, and internal reports with professional layouts, data visualizations, and on-brand design that enhances the message.', '["ChatGPT", "Canva", "Google Slides"]', 1400, 'design', 'Flexible', '1 week'),
('ai-infographic-creator', 'AI Infographic Designer', 'Data Visualization', 'Turn data into engaging infographics', 'Use AI to transform complex data into clear, engaging infographics. Design charts, diagrams, and visual stories that make information easy to understand and share. Create templates for recurring data visualization needs.', '["Claude", "Canva", "Visme"]', 1600, 'design', 'Flexible', '1 week'),
('ai-thumbnail-designer', 'AI YouTube Thumbnail Designer', 'Video Thumbnails', 'Create click-worthy video thumbnails', 'Design high-converting YouTube and social media thumbnails using AI to test concepts, analyze competitor thumbnails, and optimize for click-through rates. Create consistent branding while maximizing viewer engagement.', '["Midjourney", "Photoshop", "Canva"]', 1200, 'design', 'Flexible', '3 days'),
('ai-email-designer', 'AI Email Template Designer', 'Email Marketing Design', 'Design responsive email templates', 'Create beautiful, responsive email templates using AI assistance. Ensure mobile compatibility, test across email clients, maintain brand consistency, and optimize for engagement. Build reusable template libraries.', '["Claude", "Figma", "Mailchimp"]', 1500, 'design', 'Flexible', '1 week'),
('ai-packaging-designer', 'AI Packaging Design Consultant', 'Product Packaging', 'Design product packaging and labels', 'Create packaging designs using AI to generate concepts, ensure regulatory compliance, and prepare print-ready files. Design labels, boxes, and packaging materials that stand out on shelves and online.', '["Midjourney", "Illustrator", "Photoshop"]', 1900, 'design', 'Flexible', '2 weeks'),
('ai-brand-stylist', 'AI Brand Style Guide Creator', 'Brand Guidelines', 'Develop comprehensive brand style guides', 'Use AI to create detailed brand style guides including color palettes, typography, logo usage, tone of voice, and design examples. Ensure brand consistency across all touchpoints and create easy-to-follow guidelines.', '["Claude", "Figma", "Google Docs"]', 2000, 'design', 'Flexible', '2 weeks'),
('ai-illustration-assistant', 'AI Illustration Specialist', 'Custom Illustrations', 'Create custom illustrations for brands', 'Generate custom illustrations using AI tools for websites, apps, marketing materials, and publications. Work in various styles, create character designs, and produce original artwork that enhances brand storytelling.', '["Midjourney", "Procreate", "Illustrator"]', 1800, 'design', 'Flexible', '1 week');
